# Generated by Django 4.1.5 on 2023-01-29 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie_stands', '0002_alter_cookiestand_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
